In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
df = pd.read_csv(r"/content/drive/My Drive/Colab Notebooks/first_dataset/RAJESH/Of_Cr.csv",index_col='timestamp')

In [5]:
df.describe()

pwr
count  8760.000000
mean      3.331440
std       1.067158
min       1.000000
25%       2.425000
50%       3.225000
75%       4.175000
max       6.475000

In [6]:
def load_data(data, seq_len):
    X = []
    y = []
    #print(len(data))
    for i in range(seq_len, len(data)):
        X.append(data.iloc[i-seq_len : i, 0])
        y.append(data.iloc[i, 0])
        #print(y)
   
    
    return [X, y]

In [7]:
seq_len = 24 #choose sequence length

X, y= load_data(df, seq_len)

In [8]:
import tensorflow as tf
import sklearn.preprocessing
from keras.layers import Dense,Dropout,LSTM,Bidirectional
from keras.models import Sequential

In [10]:
# define model
model = Sequential()
model.add(Bidirectional(LSTM(36, activation='tanh', return_sequences=False), input_shape=(24,1)))
#model.add(Bidirectional(LSTM(24, activation='tanh')))
#model.add(Dropout(0.5))
model.add(Dense(1))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (None, 72)               10944     
 l)                                                              
                                                                 
 dense (Dense)               (None, 1)                 73        
                                                                 
Total params: 11,017
Trainable params: 11,017
Non-trainable params: 0
_________________________________________________________________


In [11]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,loss="MSE")

In [ ]:
history= model.fit(X_train, y_train, epochs=300, batch_size=128)

Epoch 1/300
63/63 [==============================] - 5s 24ms/step - loss: 3.8445
Epoch 2/300
63/63 [==============================] - 1s 24ms/step - loss: 1.1632
Epoch 3/300
63/63 [==============================] - 2s 24ms/step - loss: 0.9107
Epoch 4/300
63/63 [==============================] - 1s 23ms/step - loss: 0.7828
Epoch 5/300
63/63 [==============================] - 1s 23ms/step - loss: 0.7018
Epoch 6/300
63/63 [==============================] - 1s 24ms/step - loss: 0.6589
Epoch 7/300
63/63 [==============================] - 1s 24ms/step - loss: 0.6516
Epoch 8/300
63/63 [==============================] - 1s 23ms/step - loss: 0.6348
Epoch 9/300
63/63 [==============================] - 1s 24ms/step - loss: 0.6092
Epoch 10/300
63/63 [==============================] - 1s 23ms/step - loss: 0.5972
Epoch 11/300
63/63 [==============================] - 1s 24ms/step - loss: 0.6005
Epoch 12/300
63/63 [==============================] - 1s 23ms/step - loss: 0.5857
Epoch 13/300
63/63 [=====

In [ ]:
train_prediction=model.predict(X_train)
test_prediction=model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from math import sqrt

In [ ]:
rmse_train = sqrt(mean_squared_error(y_train, train_prediction))
rmse_test = sqrt(mean_squared_error(y_test, test_prediction))
mae_train=mean_absolute_error(y_train, train_prediction)
mae_test=mean_absolute_error(y_test, test_prediction)

print('RMSE for BiLSTM Model for training is:',rmse_train)
print('RMSE for BiLSTM Model for testing is:',rmse_test)
print('MAE for BiLSTM Model for training is:',mae_train)
print('MAE for BiLSTM Model for testing is:',mae_test)

RMSE for BiLSTM Model for training is: 0.5150298411344805
RMSE for BiLSTM Model for testing is: 0.5231975341059948
MAE for BiLSTM Model for training is: 0.40217556414645095
MAE for BiLSTM Model for testing is: 0.4065220018379265


In [ ]:
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (12,8)
plt.plot(test_prediction,label='BiLSTM_Predictions')
plt.plot(y_test,label='Actual value')
plt.legend(loc="upper left")
plt.show()

In [ ]:
y_test=y_test.reshape(-1,1)

y_test[0],test_prediction[0]

(array([2.2249999]), array([2.8303905], dtype=float32))

In [ ]:
d1=[]
for i in range(len(y_test)):
    d1.append(y_test[i]-test_prediction[i])
    
print(d1)

[array([-0.60539055]), array([0.08024812]), array([-0.55765343]), array([-0.41855431]), array([-0.57498288]), array([1.1873045]), array([1.62094736]), array([-0.47928047]), array([0.08977461]), array([-0.28323364]), array([-0.22308636]), array([-0.74219274]), array([-0.37936258]), array([-0.13681364]), array([-0.15104103]), array([0.16720772]), array([0.15611839]), array([0.36552191]), array([-0.94201422]), array([-0.96079731]), array([-0.11984682]), array([0.14189339]), array([-0.50716519]), array([-0.03400183]), array([-0.41820836]), array([-0.49723411]), array([-0.10711074]), array([0.15470099]), array([-0.30947447]), array([0.36027932]), array([0.16575193]), array([0.17245007]), array([-0.2860198]), array([-0.42477369]), array([-0.39283657]), array([-0.71879125]), array([0.18388319]), array([-0.0970993]), array([-0.18030787]), array([0.44194698]), array([-0.08766699]), array([0.5997076]), array([0.48294497]), array([0.00750923]), array([-0.18868566]), array([-0.11659765]), array([-

In [ ]:
d1.sort()
# Range of error value
max(d1),min(d1)

(array([2.13057017]), array([-1.54440045]))

In [ ]:
max(d1)-min(d1)

array([3.67497063])

In [ ]:
neg=[]
pos=[]
for i in range(len(d1)):
  if(d1[i]<0):
    neg.append(d1[i])
  if(d1[i]>0):  
    pos.append(d1[i])

In [ ]:
len(neg),len(pos)

(359, 337)